$(document).ready(function() {
    $('#example').DataTable( {
        "scrollY":        "",
        "scrollCollapse": false,
        "paging":         true,
		"ordering": false,
        "info":     true,
		"searching": false,
    } );
} );